name: Code Checker
permissions:
  contents: read
  pull-requests: write

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - uses: davidslusser/actions_python_ruff@731cc86ef21fa072694e44110af560e5426b4347  # v1.0.2

  codespell:
    runs-on: ubuntu-latest
    name: "codespell"
    steps:
      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630  # v2.1