name: Release
permissions:
  contents: write
  pull-requests: write

on:
  push:
    # release on tag push
    tags:
      - '*'

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Update debian changelog
        run: |
          sudo apt-get update
          sudo apt-get install devscripts
          debchange -v "`git describe --tags | sed -e "s|v||"`" -b -M --distribution noble "ci build"

      - name: Build deb packages
        uses: jtdor/build-deb-action@77e660b49ec8a92ef36e28f577317e8577a10e3e  # v1.9.0
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ubuntu:noble
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: blueprint-compiler gtk-update-icon-cache gobject-introspection libgtk-4-dev libadwaita-1-dev git python3-pydbus

      - name: Upload deb files
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: packages
          path: ./debian/artifacts/*.deb

      - name: Build rpm packages
        uses: janbrummer/build-rpm-action@main
        with:
          spec-file: "infocenter.spec"

      - name: Upload rpm files
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: "rpm-packages"
          path: ./rpm/artifacts/

  create_release:
    name: Create Release
    needs: [packaging]
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      # download all artifacts to project dir
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16  # v4.1.8

      - name: Generate changes file
        uses: sarnold/gitchangelog-action@915234f151ceffb7a8c4f76de77e4ae321087b8f  # v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda  # v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: CHANGES.md
          draft: false
          prerelease: false
          files: |
            packages/*.deb
