name: RedHat packages
permissions:
  contents: read
  pull-requests: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-rpms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: Build rpm packages
      uses: janbrummer/build-rpm-action@main
      with:
        spec-file: "infocenter.spec"

    - name: Upload rpm files
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
      with:
        name: "rpm-packages"
        path: ./rpm/artifacts/